# Generated by Django 4.2.4 on 2024-04-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='anneeFin',
            new_name='year_end',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='anneeDebut',
            new_name='year_start',
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('year_start', 'year_end')},
        ),
    ]
