# Generated by Django 4.2.4 on 2024-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_promotions', '0002_rename_anneefin_promotion_year_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='filiere',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='libelle',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='coefficient',
            old_name='classe',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='coefficient',
            old_name='matiere',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='coefficient',
            old_name='valeur',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='denomination',
            new_name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tutor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coefficient',
            unique_together={('subject', 'classroom')},
        ),
    ]
