# Generated by Django 4.2.4 on 2024-04-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_promotions', '0003_rename_filiere_classroom_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_adminstrator',
            new_name='is_administrator',
        ),
    ]
