# Generated by Django 4.2.4 on 2024-04-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_promotions', '0005_user_age_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
