# Generated by Django 4.2.4 on 2024-04-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_promotions', '0007_student_father_contact_student_mother_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
