# Generated by Django 4.2.4 on 2024-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_promotions', '0008_remove_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(choices=[('2nde', 'Seconde'), ('1ere', 'Premiere'), ('Tle', 'Terminale')], max_length=9, verbose_name='Code de la classe'),
        ),
    ]
