# Generated by Django 4.2.4 on 2024-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_promotions', '0009_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
