# Generated by Django 4.2.4 on 2024-04-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_promotions', '0010_alter_subject_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instruct',
            unique_together={('promotion', 'classroom', 'subject')},
        ),
    ]
