# Generated by Django 4.2.4 on 2024-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coefficient',
            old_name='matiereCoefficient',
            new_name='matiere',
        ),
        migrations.RenameField(
            model_name='coefficient',
            old_name='valeurCoefficient',
            new_name='valeur',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='classeMatiere',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='filiereMatiere',
        ),
        migrations.AddField(
            model_name='coefficient',
            name='classe',
            field=models.ManyToManyField(related_name='matieres_autorisees', to='classes.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='coefficient',
            name='filiere',
            field=models.ManyToManyField(related_name='filieres_autorisees', to='classes.filiere', verbose_name='Filiere'),
        ),
    ]
