# Generated by Django 4.2.4 on 2024-03-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_matierecoefficient_coefficient_matiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='codeMatiere',
            field=models.CharField(max_length=9, verbose_name='Code '),
        ),
    ]
