# Generated by Django 4.2.4 on 2024-03-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_matiere_codematiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coefficient',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='coefficient',
            name='filiere',
        ),
        migrations.AddField(
            model_name='coefficient',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='coefficient',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.filiere', verbose_name='Filiere'),
        ),
    ]
