# Generated by Django 4.2.4 on 2024-03-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_coefficient_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devoir',
            old_name='codeDevoir',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='devoir',
            old_name='denominationDevoir',
            new_name='denomination',
        ),
        migrations.RenameField(
            model_name='devoir',
            old_name='typeDevoir',
            new_name='type',
        ),
    ]
