# Generated by Django 4.2.4 on 2024-04-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_rename_codedevoir_devoir_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='codeClasse',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='classe',
            old_name='libelleClasse',
            new_name='libelle',
        ),
    ]
