# Generated by Django 4.2.4 on 2024-04-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_rename_codedevoir_devoir_code_and_more'),
        ('users', '0003_alter_eleve_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eleve',
            unique_together={('user', 'promotion')},
        ),
    ]
